### ISSUE TITLE
Sign-up  and  Sign-in  Auth

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#1]
Need backend for Sign-in and Sign-up Authentication.

**Comment by nimit2801** [comment]
Hey, @Godwindaniel10 Do you want to use firebase or auth from scratch?

**Comment by godwin-morwin** [comment]
@nimit2801 Auth from scratch ☑️

**Comment by godwin-morwin** [comment]
@nimit2801 , hi are you still working on this issue?

**Comment by nimit2801** [comment]
> 
> 
> @nimit2801 , hi are you still working on this issue?

Hey, I got stuck up in something, thanks for reminding me.
I'll send a bunch of options for the database here!

**Comment by godwin-morwin** [comment]
Aiit, will be expecting

**Comment by nimit2801** [comment]
So I would like to know your suggestion on this:
1. Would you want the HTML/CSS/js files to be shipped with an express server or
2. You want me to make an Authentication Route API with express which interacts with your static files (This one would have some security issues)

If you're going with the first one, we've to create the server and ship all files (HTML/CSS/js) in a public folder or somewhere. Also, this would change how the project is deployed on Vercel!

**Comment by godwin-morwin** [comment]
hi, what do you mean by ( change how the project is deployed on Vercel! ). and actually I dont have too much experience on backend , nut i think you should use the one that suits and worked best

**Comment by nimit2801** [comment]
> 
> 
> hi, what do you mean by ( change how the project is deployed on Vercel! ). and actually I dont have too much experience on backend , nut i think you should use the one that suits and worked best

So right now I guess you're shipping static HTML/CSS/JS files on Vercel!
[This Link](https://vercel.com/guides/deploying-a-mongodb-powered-api-with-node-and-vercel) would help you to know the process! Now when we've got a server it changes the rendering of files!

**Comment by godwin-morwin** [comment]
aiit, meaning i will have to change the way i run my project

**Comment by godwin-morwin** [comment]
hi

**Comment by nimit2801** [comment]
Hey, @Godwindaniel10 hows is it going. I think I can make an API for the backend separately here in the repo. Then you can deploy it with your vercel or somewhere. Then you can use your frontend logic to authenticate users with a login and all. This is the only way I found out without actually changing the existing project. Thoughts?

**Comment by godwin-morwin** [comment]
wow, this do be great

**Comment by godwin-morwin** [comment]
hi, hope you having a good day.

have you started working on this issue ?

**Comment by nimit2801** [comment]
I'm busy with some side projects and things, so will make a PR End of the week. ✅

**Comment by godwin-morwin** [comment]
> I'm busy with some side projects and things, so will make a PR End of the week.

aiit, that do be awesome
