### ISSUE TITLE
Create a Landing page

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#13]

**Comment by apurvalal** [comment]
I can work on this issue.

**Comment by godwin-morwin** [comment]
Sure , go ahead 🤝

**Comment by godwin-morwin** [comment]
Sure , go ahead 🤝

**Comment by apurvalal** [comment]
Do you want me to make the home.html as the landing page or a separate landing page?
Also let me know if you have any particular designs or examples you like.

**Comment by godwin-morwin** [comment]
Exactly, make the home.html page the landing page .

You should also change the file name to ( landing-page.html )

**Comment by godwin-morwin** [comment]
hi @flaregunner , whats the update ?

**Comment by apurvalal** [comment]
It will be done by Monday or Tuesday if that is okay with you. I had some unexpected work to do.

**Comment by godwin-morwin** [comment]
aiit, tuesday will do.
