### ISSUE TITLE
Redesign SIgn in page containing form fields

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#14]
Redesign signing page containing form input field.

sign-in.html

**Comment by Justobioma** [comment]
Hello,
Do you have a particular design in mind?

**Comment by godwin-morwin** [comment]
hi @Justobioma , i dont have a design of choice in mind , but you can come up with a very cool and  stunning design.

**Comment by Justobioma** [comment]
ok.I will give it a try from next week. Cheers

**Comment by godwin-morwin** [comment]
aiit
