### ISSUE TITLE
Create an image slider

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#2]
Create an image slider on the form page with a maximum of 4 different images.
section to include slider is indicated in the image below.

You can include agricultural images of your choice. (Not compulsory)
 

![make it n image slider](https://user-images.githubusercontent.com/54848535/118700504-a7d6fb80-b80a-11eb-8c8d-8d1602f820ed.JPG)

**Comment by DuanLeeWatkins** [comment]
Hello, I would like to solve your issue.

**Comment by godwin-morwin** [comment]
Thanks @DuanLeeWatkins , you can fork the repo and start working on the issue 😊☑️. 

Good luck ...🥂

**Comment by DuanLeeWatkins** [comment]
@Godwindaniel10 I submitted a pull request

**Comment by godwin-morwin** [comment]
@DuanLeeWatkins the image slider is not working yet , you should check and fix the issue , thanks.

**Comment by godwin-morwin** [comment]
@DuanLeeWatkins i think why it isnt working is the gsap cdn 


![Capture](https://user-images.githubusercontent.com/54848535/119798994-9610ea80-bed3-11eb-9ec4-46bc18d5c84d.PNG)

**Comment by DuanLeeWatkins** [comment]
@Godwindaniel10 ok I will take a look at it.

**Comment by godwin-morwin** [comment]
@DuanLeeWatkins ok thanks

**Comment by godwin-morwin** [comment]
@DuanLeeWatkins hi, are you still working on this issue?

**Comment by DuanLeeWatkins** [comment]
Hi! I apologize. I've gotten so busy. I have not been able to work on it.

**Comment by godwin-morwin** [comment]
@DuanLeeWatkins aiit, i understand ., take your time .......
