### ISSUE TITLE
Create an HTML page for ( Lettuce vegetable )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#24]
Create a ( lettuce.html ) page. include in the page all things about ( Lettuce Vegetable ) e.g - about Lettuce vegetable and how to plant, grow and care for lettuce vegetable.

Tip: you can search on google for the topic ( about Lettuce Vegetable ), find the one that explains full details on ( what is lettuce vegetable and How to plant and grow lettuce vegetable ), then implement it on the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( lettuce vegetable and how to plant and grow it );

NOTE: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar  link shown in the video below

https://user-images.githubusercontent.com/54848535/123489475-f8135b80-d609-11eb-8b15-a9050af4362b.mp4

**Comment by Saif-S** [comment]
i would like to work on this one.

**Comment by godwin-morwin** [comment]
you are good to go
