### ISSUE TITLE
Create an HTML page for ( Cabbage Vegetable )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#25]
Create a ( cabbage.html ) page. include in the page all things about (Cabbage Vegetable ) e.g - about Cabbage vegetable and how to plant, grow and care for Cabbage vegetable.

Tip: you can search on google for the topic ( about Cabbage  Vegetable ), find the one that explains full details on ( what is cabbage vegetable and How to plant and grow cabbage vegetable ), then implement it on the HTML page.

OPTIONAL: you can also embed a YouTube video describing (Cabbage  vegetable and how to plant and grow it );

NOTE: you can go through other HTML pages in the project to understand how to structure the layout.

link the Cabbage.html page to the navbar link shown in the video below: 

https://user-images.githubusercontent.com/54848535/123489811-b3d48b00-d60a-11eb-96ce-4b2c1809aca6.mp4

**Comment by Saif-S** [comment]
I would like to work on this page, If its not taken?

**Comment by godwin-morwin** [comment]
@Saif-S , you can go ahead 🤝
