### ISSUE TITLE
Create an HTML page for ( Lemon vegetable )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#26]
Create a ( Lemon.html ) page. include in the page all things about ( Lemon Vegetable ) e.g - about Lemon vegetable and how to plant, grow and care for Lemon vegetable.

Tip: you can search on google for the topic ( about Lemon Vegetables), find the one that explains full details on ( what is Lemon vegetable and How to plant and grow Lemon vegetable ), then implement it on the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Lemon vegetable and how to plant and grow it );

NOTE: you can go through other HTML pages in the project to understand how to structure the layout.

link the Lemon.html page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/123490362-ca2f1680-d60b-11eb-88f4-aae67f530bfd.mp4

**Comment by nishit-prasad** [comment]
Hello, I'm new to contribution. I would like to work on this if this is not taken?

**Comment by godwin-morwin** [comment]
you are good to go. check other html pages to have an insight of how the layout should look like

**Comment by nishit-prasad** [comment]
Sounds good! Thank you.

**Comment by nishit-prasad** [comment]
Update: Half-way done. Just trying to find right info/texts for the HTML page.

**Comment by godwin-morwin** [comment]
you can search on google for full details of lemon-vegetable , then copy and paste to this page . 

you should see how other html page looks like

**Comment by nishit-prasad** [comment]
@Godwindaniel10 PR is up and ready.
