### ISSUE TITLE
Redesign the Home page 

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#29]
Redesign the home page with a stunning design of your choice 
The header image should be an image slider with max of 3 different images related to agriculture ( images of your choice ).

**Comment by nishit-prasad** [comment]
Would you like to change the tech stack a little bit and migrate to React for better DOM experience?
It will save a lot of HTML file rendering and the pages/routes can be configured via server.

I am working and learning as I go and thought I can share my insights here (what's better than contributing for the right reasons).

**Comment by godwin-morwin** [comment]
hmm, buh i dont know how to work with react .

not yet

**Comment by nishit-prasad** [comment]
Maybe we can start small and then slowly transform?

**Comment by godwin-morwin** [comment]
i think that will be transformed in the future
