### ISSUE TITLE
Create an HTML page for ( Broccoli Vegetable )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#33]
Create a (Broccoli .html ) page. include in the page all things about ( Broccolli  Vegetable ) e.g - about Broccoli vegetable and how to plant, grow and care for Broccoli  vegetable.

Tip: you can search on google for the topic ( about Broccolli  Vegetable ), find the one that explains full details on ( what is Broccoli vegetable and How to plant and grow Broccoli  vegetable ), then implement it on the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Broccoli  vegetable  );

NOTE: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/124008505-64a8a480-d9d4-11eb-9b7f-dfab90b86980.mp4

**Comment by Saif-S** [comment]
I would like to work on this one.

**Comment by godwin-morwin** [comment]
always , sure

**Comment by Saif-S** [comment]
Please review and merge.
