### ISSUE TITLE
Create an HTML page for ( Spinach vegetable )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#34]
Create a ( Spinach.html ) page. include in the page all things about ( Spinach Vegetable ) e.g - about Spinach vegetable and how to plant, grow and care for Spinach vegetable.

Tip: you can search on google for the topic ( about Spinach Vegetable ), find the one that explains full details on ( what is Spinach vegetable and How to plant and grow Spinach vegetable ), then implement it on the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Spinach vegetable );

NOTE: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below: 

https://user-images.githubusercontent.com/54848535/124009255-4b542800-d9d5-11eb-8311-c169549401e3.mp4

**Comment by Saif-S** [comment]
I would like to work on this.

**Comment by godwin-morwin** [comment]
sure

**Comment by Saif-S** [comment]
please review and approve the pull request

**Comment by godwin-morwin** [comment]
thanks

**Comment by godwin-morwin** [comment]
great
