### ISSUE TITLE
Create an HTML page for ( Cauliflower vegetable )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#35]
Create a ( Cauliflower.html ) page. include in the page all things about ( Cauliflower Vegetable ) e.g - about Cauliflower vegetable and how to plant, grow and care for Cauliflower vegetable.

Tip: you can search on google for the topic ( about Cauliflower Vegetable ), find the one that explains full details on ( what is Cauliflower vegetable and How to plant and grow Cauliflower vegetable ), then implement(Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Cauliflower vegetable );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/124010690-08934f80-d9d7-11eb-974d-a0b9e9d1eb19.mp4

**Comment by Srinu126** [comment]
I believe  I can add this html page. can you assign it to me

**Comment by Saif-S** [comment]
I would like to work on this.

**Comment by Saif-S** [comment]
Please review and merge.
