### ISSUE TITLE
Create an HTML page for ( Garlic )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#37]
Create a ( Garlic.html ) page. include in the page all things about ( Garlic  ) e.g - about Garlic and how to plant, grow and care for Garlic.

Tip: you can search on google for the topic ( about Garlic ), find the topic that explains full details on ( what is Garlic  and How to plant and grow Garlic ), then implement (Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Garlic );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/124011792-4cd31f80-d9d8-11eb-8c5c-a43d22da34a5.mp4

**Comment by Saif-S** [comment]
I would like to work on this.

**Comment by godwin-morwin** [comment]
go ahead

**Comment by Saif-S** [comment]
Done, please review and approve the pull request.
