### ISSUE TITLE
"About" button of webpage isn't working!

### ISSUE THREAD

**Issue by GaurPeeyush** [Godwindaniel10/AgriculHub#39]
![Screenshot (276)](https://user-images.githubusercontent.com/81735768/124229956-05f63e80-db2c-11eb-86e2-4e0303c4969f.png)
The "About" button below the Agrichub logo isn't working!
Needs to be fixed using the proper hyperlink.

**Comment by godwin-morwin** [comment]
right, but the about page is not included yet , just the button.

But i do like if you can create an about.html page as well, and that should fix the issue on #10 , then float the about button to the  end-right .

i can assign the issues to you if you would like to work on it.

**Comment by GaurPeeyush** [comment]
> right, but the about page is not included yet , just the button.
> 
> But i do like if you can create an about.html page as well, and that should fix the issue on #10 , then float the about button to the end-right .
> 
> i can assign the issues to you if you would like to work on it.

You have to give me the content to be added to the "About" page, then only I can work on that!

**Comment by godwin-morwin** [comment]
right, give me some minute

**Comment by GaurPeeyush** [comment]
> right, give me some minute

Sure!

**Comment by godwin-morwin** [comment]
@GaurPeeyush Page has been updated . thanks for your contribution
