### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#41]
make the second paragraph aligned with the upper header, as shown in the image below.

![text-algnment-agrichub](https://user-images.githubusercontent.com/54848535/125139298-2fa0fe00-e108-11eb-9980-5e67879bef79.JPG)

**Comment by MAZ12211** [comment]
I would like to work on this issue.

**Comment by godwin-morwin** [comment]
sure , go ahead
