### ISSUE TITLE
Align HTML  checkbox 

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#45]
align the checkbox with the text. as shown below 

![Captureagh](https://user-images.githubusercontent.com/54848535/125156880-c0ef8f00-e15f-11eb-8f2b-f85644826f8c.PNG)

**Comment by Saif-S** [comment]
i would like to work on this

**Comment by godwin-morwin** [comment]
sure

**Comment by Saif-S** [comment]
please review and merge
