### ISSUE TITLE
Create an HTML page for ( Swiss chard vegetable )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#52]
Create a ( swiss-chard.html ) page. include in the page all things about ( swiss-chard Vegetable ) e.g - about swiss-chard vegetable and how to plant, grow and care for the swiss-chard vegetable.

Tip: you can search on google for the topic ( about swiss-chard Vegetables), find the one that explains full details on ( what is a swiss-chard vegetable and How to plant and grow swiss-chard vegetable ), then implement(Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( swiss-chard vegetable );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/125200368-b10ca380-e262-11eb-9271-3a1098d0cf8c.mp4

**Comment by Saif-S** [comment]
I will work on this one.
