### ISSUE TITLE
Create an HTML page 

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#53]
Create a ( artichoke.html ) page. include in the page all things about ( artichoke Vegetable ) e.g - about artichoke vegetable and how to plant, grow and care for the artichoke vegetable.

Tip: you can search on google for the topic ( about artichoke Vegetables), find the one that explains full details on ( what is an artichoke vegetable and How to plant and grow an artichoke vegetable ), then implement(Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( artichoke vegetable );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/125200453-2aa49180-e263-11eb-94a6-992a40e5c61f.mp4

**Comment by Saif-S** [comment]
working on this one.
