### ISSUE TITLE
Create an HTML page for ( Beetroot Vegetable ) 

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#56]
Create a ( Beetroot.html ) page. include in the page all things about ( Beetroot Vegetable ) e.g - about Beetroot vegetable and how to plant, grow and care for the Beetroot vegetable.

Tip: you can search on google for the topic ( about Beetroot Vegetables), find the one that explains full details on ( what is a Beetroot vegetable and How to plant and grow a Beetroot vegetable ), then implement(Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Beetroot vegetable );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/125200837-76a40600-e264-11eb-9671-c54d3a0b4434.mp4

**Comment by Saif-S** [comment]
I would like to work on this.

**Comment by Saif-S** [comment]
Please review and merge
