### ISSUE TITLE
Create an Html page for ( Capsicum Vegetable ) 

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#57]
Create a ( Capsicum.html ) page. include in the page all things about ( Capsicum Vegetable ) e.g - about Capsicum vegetable and how to plant, grow and care for the Capsicum vegetable.

Tip: you can search on google for the topic ( about Capsicum Vegetables), find the one that explains full details on ( what is a Capsicum vegetable and How to plant and grow a Capsicum vegetable ), then implement(Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Capsicum vegetable );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/125201140-aef81400-e265-11eb-9dcc-573c9d072fcf.mp4

**Comment by UchilDeepika** [comment]
I would like to work on this page if it's not yet taken.

**Comment by godwin-morwin** [comment]
sure
