### ISSUE TITLE
Create an HTML page for ( Carrot vegetable )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#58]
Create a ( Carrot.html ) page. include in the page all things about ( Carrot Vegetable ) e.g - about Carrot vegetable and how to plant, grow and care for the Carrot vegetable.

Tip: you can search on google for the topic ( about Carrot Vegetables), find the one that explains full details on ( what is a Carrot vegetable and How to plant and grow a Carrot vegetable ), then implement(Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Carrot vegetable );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/125201316-7e64aa00-e266-11eb-93c6-3e574423fc7e.mp4

**Comment by Saif-S** [comment]
I would like to work on this.
