### ISSUE TITLE
Create an HTML page for ( Celeriac vegetable ) 

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#59]
Create a ( Celeriac.html ) page. include in the page all things about ( Celeriac Vegetable ) e.g - about Celeriac vegetable and how to plant, grow and care for the Celeriac vegetable.

Tip: you can search on google for the topic ( about Celeriac Vegetables), find the one that explains full details on ( what is a Celeriac vegetable and How to plant and grow a Celeriac vegetable ), then implement(Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Celeriac vegetable );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/125201383-c71c6300-e266-11eb-81c2-1a791ab50371.mp4

**Comment by Saif-S** [comment]
Working on this one.
