### ISSUE TITLE
Create footer section

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#6]
Do not worry about the details to be included in the footer, i will update that later when you are done creating the footer section

**Comment by Beatrix-droid** [comment]
can i work on this please?

**Comment by Beatrix-droid** [comment]
in which html file should i put the footer section ?

**Comment by godwin-morwin** [comment]
@Beatrix-droid sure go ahead, include the footer on all HTML pages except the sign up page

**Comment by Beatrix-droid** [comment]
thank you!

**Comment by Beatrix-droid** [comment]
branch has been restored and a new PR has been submitted. Now working on the web page. Will push changes to that same branch
