### ISSUE TITLE
Create an HTML page for ( Celery Vegetable ) 

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#60]
Create a ( Celery.html ) page. include in the page all things about ( Celery Vegetable ) e.g - about Celery vegetable and how to plant, grow and care for the Celery vegetable.

Tip: you can search on google for the topic ( about Celery Vegetables), find the one that explains full details on ( what is a Celery vegetable and How to plant and grow a Celery vegetable ), then implement(Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Celery vegetable );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/125201605-c932f180-e267-11eb-834c-42c436aa46e7.mp4

**Comment by Saif-S** [comment]
I would like to work on this.

**Comment by godwin-morwin** [comment]
thanks dude
