### ISSUE TITLE
Create an HTML page for ( Fennel vegetable ) 

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#61]
Create a ( Fennel.html ) page. include in the page all things about ( Fennel Vegetable ) e.g - about Fennel vegetable and how to plant, grow and care for the Fennel vegetable.

Tip: you can search on google for the topic ( about Fennel Vegetables), find the one that explains full details on ( what is a Fennel vegetable and How to plant and grow a Fennel vegetable ), then implement(Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Fennel vegetable );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/125201659-039c8e80-e268-11eb-99c3-b6308672ba6e.mp4

**Comment by Saif-S** [comment]
working on this one
