### ISSUE TITLE
Create an HTML page for ( Chokos Vegetable )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#62]
Create a ( Chokos.html ) page. include in the page all things about ( Chokos Vegetable ) e.g - about Chokos vegetable and how to plant, grow and care for the Chokos vegetable.

Tip: you can search on google for the topic ( about Chokos Vegetables), find the one that explains full details on ( what is a Chokos vegetable and How to plant and grow a Chokos vegetable ), then implement(Copy and paste ) the information to the HTML page.

OPTIONAL: you can also embed a YouTube video describing ( Chokos vegetable );

HINT: you can go through other HTML pages in the project to understand how to structure the layout.

link the HTML page to the navbar link shown in the video below:

https://user-images.githubusercontent.com/54848535/125201840-c1278180-e268-11eb-8fad-1b831a8ec553.mp4

**Comment by Saif-S** [comment]
I will work on this one.
