### ISSUE TITLE
Create an HTML section that define ( Beekeeping for beginner )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#7]
Tip: you can search on google for the topic ( Beekeeping for beginners ), find the one that explains full details on ( beekeeping for beginners) then implement it on the HTML page.

Not IMPORTANT:  you can also embed a YouTube video describing ( BeeKeeping for beginners ) 

https://user-images.githubusercontent.com/54848535/123174032-67a51180-d477-11eb-8a7f-327c6f1f9051.mp4

**Comment by maksymalist** [comment]
Hey @Godwindaniel10 I found this video (https://youtu.be/zDZDYgBkCx0) what do you think of it? Does it describe beekeeping well enough?

**Comment by godwin-morwin** [comment]
@John8790909, yes it fits best.

**Comment by maksymalist** [comment]
So should I make the page or you will?

**Comment by godwin-morwin** [comment]
@John8790909 , create the page 🤝

**Comment by maksymalist** [comment]
Ok assign me to the issue

**Comment by maksymalist** [comment]
@Godwindaniel10 I made a PR check it out
