### ISSUE TITLE
Add ( remember me ) and ( forgotten password ) text in HTML

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#72]
mock up :
![mockup sign in](https://user-images.githubusercontent.com/54848535/126198725-91a26663-5acc-4378-a390-690f589704aa.JPG)

add exactly the same as the mockup.
![mockup sign in2](https://user-images.githubusercontent.com/54848535/126198769-88eb2031-70c1-4afe-a2ef-d40b17c2afcc.JPG)

**Comment by alvarotorrestx** [comment]
Hello, I have submitted a pull request in regards to this, please review and I hope you like it! Will be more responsive once back end is added.

This is my first commit, help and pull request, hope everything went well and please provide feedback if not!
