### ISSUE TITLE
Add footer section 

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#75]

**Comment by MAZ12211** [comment]
What should be contained in the footer section though? 
Think you might need to add a description to your issue?

**Comment by godwin-morwin** [comment]
yeah, just create the footer section, I will add the details meself

**Comment by godwin-morwin** [comment]
i think the footer has been added, you just have to make it stick to bottom

**Comment by Vouyeuz** [comment]
hi Godwindaniel10, lemme do it

**Comment by godwin-morwin** [comment]
hi @Vouyeuz , i think @MAZ12211 is about to work on this issue.

But @Vouyeuz , if its open after @MAZ12211 decision, I will surely assign you.

**Comment by MAZ12211** [comment]
@Vouyeuz can work on this. I have another issue to work on.
You can assign him @Godwindaniel10

**Comment by godwin-morwin** [comment]
Aiit @MAZ12211 .

happy coding

**Comment by godwin-morwin** [comment]
@Vouyeuz , i have assigned you the issue.

**Comment by Vouyeuz** [comment]
thank you, guys.

**Comment by Vouyeuz** [comment]
@Godwindaniel10 sir, it's done. 
Please review it. 
Thank you.

**Comment by godwin-morwin** [comment]
lolzz, i am not a sir @Vouyeuz .


and you have not submitted a pr

**Comment by Vouyeuz** [comment]
sorry, miss @Godwindaniel10 , and I'm confused where is that "compare & pull request".

**Comment by Vouyeuz** [comment]
hi, I think pr have been submitted.

**Comment by godwin-morwin** [comment]
> sorry, miss @Godwindaniel10 , and I'm confused where is that "compare & pull request".

lmao, am not a miss . am a boy

**Comment by Siddhantmi** [comment]
@Godwindaniel10  is this issue is resolved?

**Comment by godwin-morwin** [comment]
> @Godwindaniel10 is this issue is resolved?

y]es
