### ISSUE TITLE
Create an HTML page that describe ( How to raise and care for horses )

### ISSUE THREAD

**Issue by godwin-morwin** [Godwindaniel10/AgriculHub#8]
Tip: you can search on google for the topic ( How to raise and care for horses ), find the one that explains full details on ( How to raise and care for horses ),  then implement it on the HTML page.

OPTIONAL:  you can also embed a YouTube video describing ( How to raise and care for horses );

Also, link the HTML page to the navbar shown in the video below

https://user-images.githubusercontent.com/54848535/123175014-f8302180-d478-11eb-9800-5fbba1d18aaa.mp4

**Comment by Beatrix-droid** [comment]
Can i work oh this one as well ? (provided of course that you are  happy with what i did on the footer section)

**Comment by godwin-morwin** [comment]
@Beatrix-droid , Aii go-ahead
